## Sevina afi amalia 2009106042

In [90]:
import pandas as pd
import seaborn as sns
import numpy as np 
from sklearn.model_selection import train_test_split

In [175]:
df = pd.read_csv("bank.csv")
df

age          job  marital  education default  balance housing loan  \
0      59.0       admin.  married  secondary      no   2343.0     yes   no   
1      56.0       admin.  married  secondary     NaN     45.0      no   no   
2      41.0   technician  married  secondary      no   1270.0     yes   no   
3      55.0     services  married  secondary      no   2476.0     yes   no   
4      54.0       admin.  married   tertiary      no    184.0      no   no   
...     ...          ...      ...        ...     ...      ...     ...  ...   
11157  33.0  blue-collar   single    primary      no      1.0     yes   no   
11158  39.0     services  married  secondary      no    733.0      no   no   
11159  32.0   technician   single  secondary      no     29.0      no   no   
11160  43.0   technician  married  secondary      no      0.0      no  yes   
11161  34.0   technician  married  secondary      no      0.0      no   no   

        contact   day month  duration  campaign  pdays  previous poutcome  \
0       unknown   5.0   may      1042         1     -1         0  unknown   
1       unknown   5.0   may      1467         1     -1         0  unknown   
2       unknown   5.0   may      1389         1     -1         0  unknown   
3       unknown   5.0   may       579         1     -1         0  unknown   
4       unknown   5.0   may       673         2     -1         0  unknown   
...         ...   ...   ...       ...       ...    ...       ...      ...   
11157  cellular  20.0   apr       257         1     -1         0  unknown   
11158   unknown  16.0   jun        83         4     -1         0  unknown   
11159  cellular  19.0   aug       156         2     -1         0  unknown   
11160  cellular   8.0   may         9         2    172         5  failure   
11161  cellular   9.0   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         NaN  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        11158 non-null  float64
 1   job        11162 non-null  object 
 2   marital    11162 non-null  object 
 3   education  11162 non-null  object 
 4   default    11137 non-null  object 
 5   balance    11154 non-null  float64
 6   housing    11162 non-null  object 
 7   loan       11162 non-null  object 
 8   contact    11162 non-null  object 
 9   day        11142 non-null  float64
 10  month      11162 non-null  object 
 11  duration   11162 non-null  int64  
 12  campaign   11162 non-null  int64  
 13  pdays      11162 non-null  int64  
 14  previous   11162 non-null  int64  
 15  poutcome   11162 non-null  object 
 16  deposit    11149 non-null  object 
dtypes: float64(3), int64(4), object(10)
memory usage: 1.4+ MB


In [130]:
df.isna().sum()

age           4
job           0
marital       0
education     0
default      25
balance       8
housing       0
loan          0
contact       0
day          20
month         0
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
deposit      13
dtype: int64

In [131]:
df.shape

(11162, 17)

## Training set 70 : Testing set 30

In [132]:
X = df.iloc[:,:-1] #Target
Y = df.iloc[:,-1] #Feature

In [133]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [134]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", X_test.shape)

Dimensi X_train :  (7813, 16)
Dimensi X_train :  (3349, 16)
Dimensi y_train :  (7813,)
Dimensi y_test :  (3349, 16)


## Normalisasi

In [135]:
from sklearn.preprocessing import MinMaxScaler

In [136]:
dAngka = df["balance"].astype("float64")*0.001
dAngka

0        2.343
1        0.045
2        1.270
3        2.476
4        0.184
         ...  
11157    0.001
11158    0.733
11159    0.029
11160    0.000
11161    0.000
Name: balance, Length: 11162, dtype: float64

In [137]:
mm = MinMaxScaler()
x_scaled = mm.fit_transform(
df[['day','age','balance']])

In [138]:
normalisasi = pd.DataFrame(x_scaled)
normalisasi.head(6)

0         1         2
0  0.133333  0.532468  0.104371
1  0.133333  0.493506  0.078273
2  0.133333  0.298701  0.092185
3  0.133333  0.480519  0.105882
4  0.133333  0.467532  0.079851
5  0.133333  0.311688  0.077762

## Standarisasi

In [139]:
from sklearn.preprocessing import StandardScaler 

In [140]:
ss = StandardScaler()
data = np.asarray(df[['day','age','balance']])
Scaled_data = ss.fit_transform(data) 

In [141]:
print("Nilai Data Sebelum scaling : ") 
print(data) 
print("Nilai standar deviasi: ", np.std(data))
print("============================================")
print("\n Nilai Data setelah scaling : ") 
print(Scaled_data) 
print("Nilai standar deviasi: ", np.std(Scaled_data)) 

Nilai Data Sebelum scaling : 
[[   5.   59. 2343.]
 [   5.   56.   45.]
 [   5.   41. 1270.]
 ...
 [  19.   32.   29.]
 [   8.   43.    0.]
 [   9.   34.    0.]]
Nilai standar deviasi:  nan

 Nilai Data setelah scaling : 
[[-1.2644784   1.49133059  0.25222699]
 [-1.2644784   1.23953978 -0.46005034]
 [-1.2644784  -0.01941423 -0.08035507]
 ...
 [ 0.39700883 -0.77478664 -0.46500962]
 [-0.90844543  0.1484463  -0.47399833]
 [-0.78976777 -0.60692611 -0.47399833]]
Nilai standar deviasi:  nan


## Data Cleaning

In [142]:
from sklearn.impute import SimpleImputer

In [143]:
df.isna().sum()

age           4
job           0
marital       0
education     0
default      25
balance       8
housing       0
loan          0
contact       0
day          20
month         0
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
deposit      13
dtype: int64

## Mengubah nilai null yang punya tipe data desimal

In [144]:
imputer = SimpleImputer(strategy = 'mean')
df["day"] = imputer.fit_transform(df[["balance"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
age           4
job           0
marital       0
education     0
default      25
balance       8
housing       0
loan          0
contact       0
day           0
month         0
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
deposit      13
dtype: int64


## Mengubah nilai null yang punya tipe data kategorikal

In [148]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["default"] = imputer.fit_transform(df[["default"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
age           4
job           0
marital       0
education     0
default       0
balance       8
housing       0
loan          0
contact       0
day           0
month         0
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
deposit      13
dtype: int64


## Mengubah nilai null yang punya tipe data bilang bulat

In [149]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["age"] = imputer.fit_transform(df[["age"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
age           0
job           0
marital       0
education     0
default       0
balance       8
housing       0
loan          0
contact       0
day           0
month         0
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
deposit      13
dtype: int64


## Data duplikat

In [164]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, job, marital, education, default, balance, housing, loan, contact, day, month, duration, campaign, pdays, previous, poutcome, deposit, jobEnc]
Index: []

In [165]:
df.drop_duplicates(inplace=True)

In [166]:
print("Setelah menggunakan fungsi drop_duplicates()") 
print("Jumlah Nilai Duplikat:",df.duplicated().sum())

Setelah menggunakan fungsi drop_duplicates()
Jumlah Nilai Duplikat: 0


## Mengubah tipe data angka menjadi kategorikal

In [167]:
from sklearn.preprocessing import OrdinalEncoder 

In [174]:
encoder = OrdinalEncoder() 
df["jobEnc"] = encoder.fit_transform(df[["job"]]) 
df.head()

age         job  marital  education default  balance housing loan  \
0  59.0      admin.  married  secondary      no   2343.0     yes   no   
1  56.0      admin.  married  secondary     NaN     45.0      no   no   
2  41.0  technician  married  secondary      no   1270.0     yes   no   
3  55.0    services  married  secondary      no   2476.0     yes   no   
4  54.0      admin.  married   tertiary      no    184.0      no   no   

   contact  day  ... duration  campaign  pdays  previous  poutcome deposit  \
0  unknown  5.0  ...     1042         1     -1         0   unknown     yes   
1  unknown  5.0  ...     1467         1     -1         0   unknown     NaN   
2  unknown  5.0  ...     1389         1     -1         0   unknown     yes   
3  unknown  5.0  ...      579         1     -1         0   unknown     yes   
4  unknown  5.0  ...      673         2     -1         0   unknown     yes   

     0    1    2  jobEnc  
0  0.0  1.0  0.0     0.0  
1  0.0  1.0  0.0     0.0  
2  0.0  1.0  0.0     9.0  
3  0.0  1.0  0.0     7.0  
4  0.0  1.0  0.0     0.0  

[5 rows x 21 columns]

## One Hot Encoding

In [172]:
from sklearn.preprocessing import OneHotEncoder 

In [173]:
encoder = OneHotEncoder(sparse=False) 
maritalEnc = encoder.fit_transform(df[["marital"]]) 
maritalEnc = pd.DataFrame(maritalEnc) 
df = df.join(maritalEnc) 
df 

age          job  marital  education default  balance housing loan  \
0      59.0       admin.  married  secondary      no   2343.0     yes   no   
1      56.0       admin.  married  secondary     NaN     45.0      no   no   
2      41.0   technician  married  secondary      no   1270.0     yes   no   
3      55.0     services  married  secondary      no   2476.0     yes   no   
4      54.0       admin.  married   tertiary      no    184.0      no   no   
...     ...          ...      ...        ...     ...      ...     ...  ...   
11157  33.0  blue-collar   single    primary      no      1.0     yes   no   
11158  39.0     services  married  secondary      no    733.0      no   no   
11159  32.0   technician   single  secondary      no     29.0      no   no   
11160  43.0   technician  married  secondary      no      0.0      no  yes   
11161  34.0   technician  married  secondary      no      0.0      no   no   

        contact   day month  duration  campaign  pdays  previous poutcome  \
0       unknown   5.0   may      1042         1     -1         0  unknown   
1       unknown   5.0   may      1467         1     -1         0  unknown   
2       unknown   5.0   may      1389         1     -1         0  unknown   
3       unknown   5.0   may       579         1     -1         0  unknown   
4       unknown   5.0   may       673         2     -1         0  unknown   
...         ...   ...   ...       ...       ...    ...       ...      ...   
11157  cellular  20.0   apr       257         1     -1         0  unknown   
11158   unknown  16.0   jun        83         4     -1         0  unknown   
11159  cellular  19.0   aug       156         2     -1         0  unknown   
11160  cellular   8.0   may         9         2    172         5  failure   
11161  cellular   9.0   jul       628         1     -1         0  unknown   

      deposit    0    1    2  
0         yes  0.0  1.0  0.0  
1         NaN  0.0  1.0  0.0  
2         yes  0.0  1.0  0.0  
3         yes  0.0  1.0  0.0  
4         yes  0.0  1.0  0.0  
...       ...  ...  ...  ...  
11157      no  0.0  0.0  1.0  
11158      no  0.0  1.0  0.0  
11159      no  0.0  0.0  1.0  
11160      no  0.0  1.0  0.0  
11161      no  0.0  1.0  0.0  

[11162 rows x 20 columns]